---

- name: Clone app repo
  git: repo={{git_repo_url}} dest={{git_repo_dir}} version={{git_repo_branch}}
  notify:
    - reload supervisor config
  tags: code

- name: Clear pip build dir
  file: path=/opt/venv/build state=absent
  tags: code

- name: Create a virtual env and install app requirements
  pip: requirements='requirements/production.txt' virtualenv=/opt/venv chdir={{git_repo_dir}}
  tags: code

- name: Install bower components
  django_manage: >
      command="bower_install -- --allow-root -f"
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars
  tags: code

- name: Run collectstatic
  django_manage: >
      command=collectstatic
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars
  tags: code

- name: Run syncdb
  django_manage: >
      command=syncdb
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars
  tags: code

- name: Run DB migrations
  django_manage: >
      command=migrate
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars
  tags: code

- name: Load fixtures
  django_manage: >
      command=loaddata
      fixtures={{item}}
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  with_items:
    - admin_user.json
    - sample_projects.json
  environment: django_env_vars
  tags: code
