---
- hosts: launcher
  remote_user: "{{remote_user}}"
  gather_facts: false
  vars_files:
    - secret_vars.yml
  roles:
    - common
    - pythondev
    - postgresql
    - memcached
    - nginx
    - uwsgi
    - redis
    - app_deployment
    - newrelic
    - supervisor
