# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network :public_network
  config.dns.tld = "dev"


  config.vm.define "launcher" do |launcher|
    launcher.vm.network :forwarded_port, guest: 80, host: 8080
    launcher.vm.network :private_network, ip: "192.168.33.10"
    launcher.vm.hostname = "launcher"
    launcher.dns.patterns = [/^launcher.dev$/, /^.*demo.dev$/]

    launcher.vm.provider :virtualbox do |vb|
        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    launcher.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
        ansible.inventory_path = "hosts/vagrant/inventory"
        ansible.sudo = true
        #ansible.tags = ['hipache', 'shipyard']
        ansible.tags = ['ssh']
    end
  end

  config.vm.define "docker" do |docker|
    docker.vm.network :private_network, ip: "192.168.33.20"
    docker.vm.hostname = "docker"

    docker.vm.provider :virtualbox do |vb|
        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    docker.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
        ansible.inventory_path = "hosts/vagrant/inventory"
        ansible.sudo = true
    end
  end

end
