---

- name: Pull the required Shipyard images
  docker_pull: repo={{item}} tag=latest
  with_items:
    - shipyard/rethinkdb
    - shipyard/shipyard
    - shipyard/shipyard-cli

- name: Start RethinkDB data container
  docker: image=shipyard/rethinkdb name=shipyard-rethinkdb-data stdin_open=yes tty=yes command="/bin/bash -l"

- name: Start RethinkDB
  docker: image=shipyard/rethinkdb volumes_from=shipyard-rethinkdb-data name=shipyard-rethinkdb stdin_open=yes tty=yes ports=8001:8080
  register: rethinkdb

- name: Wait for RethinkDB to start
  wait_for: port=28015 host={{rethinkdb['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress']}} delay=2

- name: Copy RethinkDB Upstart script
  copy: src=upstart_rethinkdb.conf dest=/etc/init/docker_rethinkdb.conf mode=0644

- name: Install RethinkDB CLI
  npm: name=recli global=yes state=latest

- name: Stop&remove the existing Shipyardcontainer, if there is one
  docker: image=shipyard/shipyard name=shipyard state=absent

- name: Start Shipyard
  docker: image=shipyard/shipyard name=shipyard links=shipyard-rethinkdb:rethinkdb ports=8080:8080 stdin_open=yes tty=yes

- name: Wait a bit until Shipyard creates the required tables
  pause: seconds=5

- name: Copy Shipyard Upstart script
  copy: src=upstart_shipyard.conf dest=/etc/init/docker_shipyard.conf mode=0644

- name: Clear Shipyard service keys table
  command: >
    recli -h {{rethinkdb['ansible_facts']['docker_containers'][0]["NetworkSettings"]["IPAddress"]}} 'r.db("shipyard").table("service_keys").delete()'

- name: Insert Shipyard service key
  command: >
    recli -h {{rethinkdb['ansible_facts']['docker_containers'][0]["NetworkSettings"]["IPAddress"]}} 'r.db("shipyard").table("service_keys").insert({description: "{{app_name}}", key: "{{shipyard_key}}"})'

- name: Clear Shipyard engines table
  command: >
    recli -h {{rethinkdb['ansible_facts']['docker_containers'][0]["NetworkSettings"]["IPAddress"]}} 'r.db("shipyard").table("config").delete()'

- name: Insert Shipyard engine
  command: >
    recli -h {{rethinkdb['ansible_facts']['docker_containers'][0]["NetworkSettings"]["IPAddress"]}}
     'r.db("shipyard").table("config").insert({engine: {Addr: "http://{{item}}:2375", Cpus: {{docker_server_cpus}}, ID: "docker", Labels: ["dev"], Memory: {{docker_server_memory}} }})'
  with_items: groups['docker']

# needed for Shipyard to pick up changes made in RethinkDB
- name: Restart Shipyard
  docker: image=shipyard/shipyard name=shipyard state=restarted
